### ISSUE TITLE
[General] Consolidate `buildwithgrove` and `path`

### ISSUE THREAD

**Issue by Olshansk** [buildwithgrove/path#32]
## Objective

Make it easier to track, organize and prioritize PATH infra related work.

## Origin Document

- [pokt-foundation/projects/infra](https://github.com/orgs/pokt-foundation/projects/17/views/1)
- [pokt-foundation/appofapps](https://github.com/pokt-foundation/appofapps)

## Goals

- Make it easier to plan and align on priorities for path, portal & related infra

## Deliverables

- [ ] Move over [pokt-foundation/projects/infra](https://github.com/orgs/pokt-foundation/projects/17/views/1) to [buildwithgrove/projects/path](https://github.com/orgs/buildwithgrove/projects/1)
- [ ] Move over [pokt-foundation/appofapps](https://github.com/pokt-foundation/appofapps) from `pokt-foundation` to `buildwithgrove`
- [x] Move over [pokt-foundation/infrastructure](https://github.com/pokt-foundation/infrastructure) from `pokt-foundation` to `buildwithgrove`
- ⚠️  IMPORTANT: DO NOT DO THIS MANUALLY. THIS MAY REQUIRE REACHING OUT TO GITHUB FOR SUPPORT IF IT IS NOT SELF SERRVE.⚠️

## Non-goals / Non-deliverables

- Any infra related working
- Manually copy & pasting everything
- ...

---

**Creator**: @Olshansk 
**Co-Owners**: @HebertCL @fredteumer

**Comment by fredteumer** [comment]
@HebertCL looks like you can script the movement of the issues from one repo to another: https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/transferring-an-issue-to-another-repository Lmk if you want me to take this clerical step or if you'd like to handle that.

When you're ready to tackle [pokt-foundation/appofapps](https://github.com/pokt-foundation/appofapps) let me know and I can move from one org to the other.

Lastly, I believe [pokt-foundation/infrastructure](https://github.com/pokt-foundation/infrastructure) is already what (https://github.com/buildwithgrove/infrastructure) and should be moved to archive. Let me know if that's correct and I can take that step.

**Comment by fredteumer** [comment]
3rd `Action Item` above was redundant and marking as completed.

**Comment by Olshansk** [comment]
@fredteumer Do you mind migrating [1] to [2] in this iteration?

[1] https://github.com/orgs/pokt-foundation/projects/17
[2] https://github.com/buildwithgrove/infrastructure/

**Comment by Olshansk** [comment]
This was done in the last sprint.
