### ISSUE TITLE
[E2E] Add E2E tests for Morse

### ISSUE THREAD

**Issue by adshmh** [buildwithgrove/path#40]
## Objective

Add E2E tests for integration with Morse.

## Origin Document

This is needed to ensure correct integration with Morse.

## Goals

- Ensure correct integration with Morse.

## Deliverables

- [ ] Code changes to add E2E tests using Morse as the relaying protocol.
- [ ] Github workflows/CI changes to run E2E tests on every PR.
- [ ] Updated docs on running Morse E2E tests.

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @adshmh
**Co-Owners**: @adshmh  @Olshansk

**Comment by Olshansk** [comment]
@adshmh Is this done?
