### ISSUE TITLE
[Envoy Proxy] API Key Auth for Backwards Compatibility with Portal

### ISSUE THREAD

**Issue by commoddity** [buildwithgrove/path#62]
## Objective

Add simple (`static`) string API Key Auth to Envoy to allow the use of `PATH` by existing `Portal` users.

## Origin Document

The Envoy Proxy feature as it currently exists[1][2] uses `JWT` token authorization from an external auth provider (`Auth0`).

This has some tradeoffs:
- **Improvement**: `PATH` is more secure than `portal-middleware` because we have refreshable JWTs.
- **Tradeoff**: `portal-middleware` uses simple basic static API keys and this solution is not backwards compatible.

References:
- [1] #47
- [2] #52

## Goals

- Enable backward compatibility during the migration from `portal-middleware` to `PATH`
- Enable two forms of authentication for development & production w/ speed & security tradeoffs

## Deliverables

- [ ] Update the `envoy/auth_server` package to handle authorizing requests using the existing `static secret key` stored in the Portal database (if the Portal App is set to require it).
- [ ] Enable ☝️ to be configurable via an ENV variable.
- [ ] Allow PATH's Envoy `Go External Auth Server` to authorize requests using the static API key about
- [ ] Introduce documentation & configuration to specify if `PATH` should be deployed via JWT or or static API key

---

**Creator**: @commoddity 
**Co-Owners**: @Olshansk @adshmh @fredteumer

**Comment by Olshansk** [comment]
@commoddity I updated the github issue deliverables & goals. PTAL when you can.

CC @adshmh for context

**Comment by commoddity** [comment]
> @commoddity I updated the github issue deliverables & goals. PTAL when you can.
> 
> CC @adshmh for context

LGTM. 

I've updated the Gateway Endpoint definition in both a new branch on PATH and in the YAML implementation inside the PADS repo. 

See comments here:
https://github.com/buildwithgrove/path-auth-data-server/pull/2#issuecomment-2482714409

If this looks good to you I will add the API key auth implementation to a new PR on PATH.

**Comment by Olshansk** [comment]
> I think whether a GatewayEndpoint should use JWT or API key auth (or no auth at all) should be determined at the level of the GatewayEndpoint 

My initial reaction is that this seems "cool" and I understand the motivation, but feels like it adds too much complexity. 

After reviewing the other PR, I'm onboard (mostly) and will leave some extra questions there.

**Comment by commoddity** [comment]
> > I think whether a GatewayEndpoint should use JWT or API key auth (or no auth at all) should be determined at the level of the GatewayEndpoint
> 
> My initial reaction is that this seems "cool" and I understand the motivation, but feels like it adds too much complexity.
> 
> After reviewing the other PR, I'm onboard (mostly) and will leave some extra questions there.

Thanks for the feedback. Addressed in further detail on the PADS PR:
https://github.com/buildwithgrove/path-auth-data-server/pull/2#issuecomment-2486815730
