### ISSUE TITLE
[Envoy Auth] Allow configuration of URL format

### ISSUE THREAD

**Issue by commoddity** [buildwithgrove/path#77]
## Objective

Allow configuration of URL format for PATH.

Currently the URL format is enforced in the code to be one of two options:
1. Without Envoy Auth - `https://<SERVICE_NAME>.<PATH_DOMAIN>/v1`
2. With Envoy Auth - `https://<SERVICE_NAME>.<PATH_DOMAIN>/v1/<GATEWAY_ENDPOINT_ID>`

This issue should allow the Gateway Operator to configure the format the URL takes, as well as the way in which the Gateway Endpoint ID is passed to Envoy Auth.

## Origin Document

Initial discussion:
https://github.com/buildwithgrove/path/pull/52#discussion_r1859632536

## Goals

- ~~Allow Gateway Operator to configure URL path segments (eg. `/v1`)~~
- Allow Gateway Operator to configure how the Gateway Endpoint ID is passed for a request

## Deliverables

- [ ] Modify Envoy Auth Server to allow passing Gateway Endpoint ID in multiple ways (eg. as part of URL path, as a header field, etc.)

## Non-deliverables

- Modify PATH's `router.go` to allow configuration of URL path segments

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @commoddity 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
@commoddity Are you going to tackle this in the next 1-2 weeks?

**Comment by commoddity** [comment]
> @commoddity Are you going to tackle this in the next 1-2 weeks or next year?

I want to tentatively say yes. I'm thinking my current work in order goes:
`Envoy w/ Tilt -> Cheatsheets for PATH & Envoy -> This issue` 

So I think getting this done before EOY is reasonable.
